name: cvnd
channels:
  - menpo
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - asn1crypto
  - backcall
  - blas
  - bleach
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - cloudpickle
  - conda
  - conda-env
  - cryptography
  - cycler
  - dask-core
  - decorator
  - entrypoints
  - eventlet
  - fontconfig
  - freetype
  - gettext
  - glib
  - gmp
  - graphite2
  - greenlet
  - h5py
  - harfbuzz
  - hdf5
  - html5lib
  - icu
  - idna
  - imageio
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libxml2
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - mkl-include
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - networkx
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openblas
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - prompt_toolkit
  - ptyprocess
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python
  - python-dateutil
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - requests
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - simplegeneric
  - sip
  - six
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - tk
  - toolz
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - libgfortran
  - ffmpeg
  - ipywidgets
  - opencv3
  - widgetsnbextension
  - magma-cuda90
  - pip:
    - pillow
    - torch
    - torchvision
    - dask
    - moviepy
    - tqdm
# prefix: /opt/conda/envs/cvnd
